### ISSUE TITLE
says, "started HTTP server" but bsimp cannot be accessed.

### ISSUE THREAD

**Issue by pegasusearl** [akrylysov/bsimp#2]
Hello, I can't get bsimp to work properly. 

I had minio instance running.
```
MinIO Object Storage Server
Copyright: 2015-0000 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2022-11-11T03-44-20Z (go1.19.3 linux/amd64)

Status:         1 Online, 0 Offline. 
API: http://192.168.8.125:9000  http://127.0.0.1:9000     
RootUser: minioadmin 
RootPass: minioadmin 
Console: http://192.168.8.125:38341 http://127.0.0.1:38341   
RootUser: minioadmin 
RootPass: minioadmin 

Command-line: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
   $ mc alias set myminio http://192.168.8.125:9000 minioadmin minioadmin

Documentation: https://min.io/docs/minio/linux/index.html

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of MinIO released 1 month ago ┃
┃ Update: Run `mc admin update`                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

```

The minio had bucket named "Music"

![Screenshot from 2023-01-03 05-01-24](https://user-images.githubusercontent.com/23167087/210280769-c9e4a3aa-3494-40c2-99ca-e978fd3e9a18.png)

this is my config file.  `config_minio.toml` located in the same directory as bsimp.
```
[s3]
region = "local"
endpoint = "http://localhost:9000"
bucket = "Music"
force_path_style = true

[s3.credentials]
id = "minioadmin" 
secret = "minioadmin"
```

# Running Result

These are commands I used to run bsimp followed by their output. It's inside bsimp's directory.

```
./bsimp -config="config_minio.toml"
2023/01/03 04:53:58 INFO started HTTP server address=:8080
```

```
./bsimp -config="config_minio.toml" -http=":8080"
2023/01/03 04:54:29 INFO started HTTP server address=:8080
```

```
./bsimp -config="config_minio.toml" -http="localhost:8080"
2023/01/03 04:54:40 INFO started HTTP server address=localhost:8080
```

```
./bsimp -config="/home/velvet/Applications/ResourcesRepository/bsimp/config_minio.toml"                       
2023/01/03 05:04:19 INFO started HTTP server address=:8080
```

```
./bsimp -config="/home/velvet/Applications/ResourcesRepository/bsimp/config_minio.toml" -http="127.0.0.1:8000"
2023/01/03 04:56:12 INFO started HTTP server address=127.0.0.1:8000
```

I can't seem to access bsimp with any of the commands above.

![Screenshot from 2023-01-03 05-04-48](https://user-images.githubusercontent.com/23167087/210280899-d3cfec0e-c622-4633-a7d9-6cb91c9919e5.png)

additionally, nothing changed in the output even after I stopped minio.

What might be the issue?

====
```
OS: Manjaro Linux x86_64 
Kernel: 5.15.85-1-MANJARO 
CPU: AMD Ryzen 5 3500 (6) @ 3.600GHz 

go version go1.19.4 linux/amd64
```

**Comment by akrylysov** [comment]
Hi! This is interesting, it works fine for me both on Linux and macOS. It seems the issue is clearly accessing the HTTP server, not the MinIO instance. Have you tried some other less common ports? Do you have a firewall enabled that would block the connections?

Here is how bsimp is configured on my Linux server - `bsimp -config=/etc/bsimp/config.toml -http=":8086"`. I can access it with `curl http://127.0.0.1:8086/library/`.

**Comment by pegasusearl** [comment]
ah I'm sorry my bad. Looks like I wrote the port wrong. The default written in `readme` is 8080 but what I'm trying to access is 8000. Thank you for your assistance.

But still, since `http://127.0.0.1:8080/` shows `404 page not found`, if I didn't come here, I would not have figured out that I need to manually type `/library` to access the page.

Perhaps an output message saying `You can access bsimp at http://127.0.0.1:8080/library` would prevent confusion.

**Comment by akrylysov** [comment]
> Perhaps an output message saying You can access bsimp at http://127.0.0.1:8080/library would prevent confusion.

Thanks for the feedback! I'll make the root path to redirect to `library`.
